# Generated by Django 5.2 on 2025-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipie_name', models.CharField(max_length=50)),
                ('recipie_ingrediants', models.CharField(max_length=300)),
                ('recipie_description', models.TextField()),
                ('recipie_image', models.FileField(upload_to='')),
            ],
        ),
    ]
