# Generated by Django 5.2 on 2025-04-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie_app', '0002_remove_recipie_recipie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_image',
            field=models.FileField(default='default.jpg', upload_to='recipie_img/'),
        ),
    ]
