# Generated by Django 5.1.3 on 2025-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie_app', '0003_recipie_recipie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='recipie_ingrediants',
            field=models.TextField(),
        ),
    ]
